### ISSUE TITLE
AMhostasset - Powershell Script to fetch HostAssets

### ISSUE THREAD

**Issue by npadmani** [Qualys/community#7]
AMHostasset - the powershell script uploaded here might be a fully woring example but for some reason, I always end up getting following, not too sure why?

```
<?xml version="1.0" encoding="UTF-8"?>
<ServiceResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://qualysapi.qualys.com/qps/xsd/2.0/am/hostasset.xsd">
  <responseCode>AUTH_CREDENTIALS_NEEDED</responseCode>
  <responseErrorDetails>
    <errorMessage>Login and password are required</errorMessage>
    <errorResolution>Make sure to pass &apos;user&apos; and &apos;password&apos; as request headers.</errorResolution>
  </responseErrorDetails>
</ServiceResponse>
```

**Comment by pmgupte** [comment]
@npadmani That is the response from Qualys API, and it means, your request does not have Qualys credentials. Does your version of script differs from what is [here](https://github.com/Qualys/community/blob/master/AMhostasset/AMhostassetAPI.ps1)? - knowingly/unknowingly?

When I set correct credentials and URL, I do not see that error, **BUT** I see it only when my request does not have `Authorization` header. I recreated that by changing [line 26](https://github.com/Qualys/community/blob/master/AMhostasset/AMhostassetAPI.ps1#L26) to following:
```
$BasicAuthFormedCredential = ""
```
Please check your script, it must be doing something wrong in/around setting `Authorization` header in the request. 

I am closing this ticket, as there is nothing wrong with the script. 
Thanks.
